[profile.default]
src = "src"
out = "out"
libs = ["lib","node_modules"]
remappings=[
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip",
    "@pythnetwork/pyth-sdk-solidity/=node_modules/@pythnetwork/pyth-sdk-solidity",
    "@pythnetwork/entropy-sdk-solidity/=node_modules/@pythnetwork/entropy-sdk-solidity"
]
build_info = true

[rpc_endpoints]
sepolia = "${ETH_SEPOLIA_RPC_URL}"


[etherscan]
sepolia = { key = "${ETH_EXPLORER_API_KEY}" }
base = { key = "${BASE_EXPLORER_API_KEY}" }
optimism = { key = "${OP_EXPLORER_API_KEY}" }